web:
  port: 8080

maintenance-events-file: /config/maintenance-events.json

storage:
  type: postgres
  path: "$GATUS_DB_URL"
  caching: true
  maximum-number-of-results: 43200
  maximum-number-of-events: 50

ui:
  title: "MaiaSolution | Status"
  header: "MaiaSolution"
  dashboard-heading: "Health Dashboard"
  dashboard-subheading: "Monitora lo stato dei servizi in tempo reale"
  dark-mode: false
  default-sort-by: "name"

endpoints:
  - name: Clack API
    group: Core
    url: "https://clackapi.maiasolution.it/health"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: Clack Frontend
    group: Core
    url: "https://clack.maiasolution.it"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
      - "[CERTIFICATE_EXPIRATION] > 48h"
